### ISSUE TITLE
Different boiling temperatures in biosteam and thermosteam

### ISSUE THREAD

**Issue by gaorkl** [BioSTEAMDevelopmentGroup/biosteam#90] opened 2022-03-31 09:14 UTC
Hi,

I am starting to use biosteam a bit, it is a very nice library.
I am trying to reproduce distillation columns from different papers, and came across a problem.

**Describe the bug**
When creating a "Methyl Acetate" Chemical in thermosteam, the boiling temperature is correct: 329.95
But if biosteam is imported before creating the Chemical, the temperature becomes 414.65.

Also, even if I make sure to import thermosteam and instanciate the chemicals before importing biosteam, this chemical in streams have the correct boiling point, but when using a distillation column the boiling point used is the wrong one.

**To Reproduce**
```python
import thermosteam as tmo
# import biosteam as bst

MA = tmo.Chemical('MethylAcetate')
print(MA.Tb)
```
With and without importing biosteam gives different results.

**Version**
 PyPI

**Comment by yoelcortes** [comment] 2022-03-31 17:45
Hi @gaorkl,

Thanks so much for posting the issue! It should be fixed now.

The problem had to do with the search algorithm acting differently after autoloading chemical metadata (identifiers). The same issue could be reproduced with the following:
```
import thermosteam as tmo
Water = tmo.Chemical('Water') # Comment out to get the correct MA
MA = tmo.Chemical('MethylAcetate')
print(MA.Tb)
```
Now the search algorithm should be consistent regardless :)

Because the identifier database (imported from https://github.com/CalebBell/chemicals) has some overlapping names, best practice is to use CASRN (instead of common names) to get the correct chemical.

Hope this helps,
Thanks!

**Comment by gaorkl** [comment] 2022-03-31 17:47
Hi!

Thank you so much for your quick reply!
I will test that tomorrow.

I have another related question, does distillation units handle the behavior of azeotropes?

Cheers

Michael

**Comment by yoelcortes** [comment] 2022-03-31 17:53
It sure does! https://biosteam.readthedocs.io/en/latest/tutorial/Unit_operation_results.html#References

Don't forget to update thermosteam and maybe biosteam (on PyPI or github) when you test it,
Thanks,

**Comment by yoelcortes** [comment] 2022-03-31 17:55
You might also find the small section on thermodynamic equilibrium in the thermosteam tutorial useful:

https://thermosteam.readthedocs.io/en/latest/tutorial/Thermosteam_in_an_hour.html#Thermodynamic-equilibrium

Thanks!

**Comment by gaorkl** [comment] 2022-04-01 10:39
Hi,

I just tested it. I am not sure I am doing it properly so I attached the script I am using.

If I am not making any mistake, the Methyl Acetate should evaporate in the distillation column. 
However it stays at the bottom of the column.
My guess is that in the distillation columns it still refers to the wrong temperature, I am not sure why.

What do you think?

```python
import thermosteam as tmo
from chemicals import CAS_from_any

CAS_A = CAS_from_any('MethylAcetate')
A = tmo.Chemical(CAS_A)

CAS_B = CAS_from_any('Methanol')
B = tmo.Chemical(CAS_B)

CAS_C = CAS_from_any('Ethanol')
C = tmo.Chemical(CAS_C)

CAS_D = CAS_from_any('Water')
D = tmo.Chemical(CAS_D)

CAS_E = CAS_from_any('AceticAcid')
E = tmo.Chemical(CAS_E)

thermo = tmo.Thermo([A, B, C, D, E])

import biosteam as bst

# Feed
bst.settings.set_thermo(thermo)
feed = bst.Stream('feed', 
                  flow=(0.2, 0.2, 0.2, 0.2, 0.2),
                  units='kmol/hr')

feed.set_total_flow(100, units='kmol/hr')
feed.set_property('T', 25, 'degC')

feed.show()

print(feed.thermo.chemicals)

D1 = bst.ShortcutColumn('D1', ins=feed,
                        outs=('distillate', 'bottoms_product'),
                        LHK=( B.CAS, C.CAS),
                        Lr=0.99999, Hr=0.99, 
                        k=2,
                        is_divided=True,
                        tray_spacing=420,
                        P=101325)

flowsheet_sys = bst.main_flowsheet.create_system('flowsheet_sys_test')
flowsheet_sys.simulate()

# See all results
flowsheet_sys.show(T='degC', P='atm', composition=True)

for chem in flowsheet_sys.outs[1].thermo.chemicals:
    print(chem, chem.Tb)

**Comment by gaorkl** [comment] 2022-04-01 16:38
Hi!

Thank you very much for your input.

I am relatively new to the field, so I might not understand all of the fine details.

But in the script that I showed you, Methyl Acetate is supposed to have the lowest boiling point of all the components. So even in the Shortcut Column model it should come up in the distillates, no?

Or I am missing something more fundamental?

Cheers

Michael

**Comment by yoelcortes** [comment] 2022-04-01 23:47
Hi Michael,

Boiling points are just part of the story. Fugacities (and hence volatilities) are a function of composition as well and they can get a little crazy, especially with polar compounds (this is the reason azeotropes exist). I just checked and BioSTEAM is actually unable to converge this shortcut column (probably because of there are so many polar compounds in high amounts; I should add a warning for this). This may be another reason why we get these odd values

If you are confident almost all the light non-keys end up in the distillate and almost all the heavy non-keys end up in the bottoms product, you should use the BinaryDistillation object (which assumes this). Otherwise, it would be best to check with chemsep.

 ```python
import biosteam as bst
A = bst.Chemical('MethylAcetate', search_ID='79-20-9')
B = bst.Chemical('Methanol', search_ID='67-56-1')
C = bst.Chemical('Ethanol', search_ID='64-17-5')
D = bst.Chemical('Water', search_ID='7732-18-5')
E = bst.Chemical('AceticAcid', search_ID='64-19-7')
bst.settings.set_thermo([A, B, C, D, E])
feed = bst.Stream('feed', 
                  flow=(0.2, 0.2, 0.2, 0.2, 0.2),
                  total_flow=100,
                  units='kmol/hr')
D1 = bst.BinaryDistillation('D1', ins=feed,
                        outs=('distillate', 'bottoms_product'),
                        LHK=(B.ID, C.ID),
                        Lr=0.99999, Hr=0.99, 
                        k=2,
                        is_divided=True,
                        tray_spacing=420,
                        P=101325)
D1.simulate()
D1.show()
D1.plot_stages()
```
Output:
```python
BinaryDistillation: D1
ins...
[0] feed
    phase: 'l', T: 298.15 K, P: 101325 Pa
    flow (kmol/hr): MethylAcetate  20
                    Methanol       20
                    Ethanol        20
                    Water          20
                    AceticAcid     20
outs...
[0] distillate
    phase: 'g', T: 328.58 K, P: 101325 Pa
    flow (kmol/hr): MethylAcetate  20
                    Methanol       20
                    Ethanol        0.2
[1] bottoms_product
    phase: 'l', T: 359.98 K, P: 101325 Pa
    flow (kmol/hr): Methanol    0.0002
                    Ethanol     19.8
                    Water       20
                    AceticAcid  20
 ```
![Figure_3](https://user-images.githubusercontent.com/29529649/161354837-e43be672-d0fe-442c-877b-1fc91dcea5cb.png)

**Comment by gaorkl** [comment] 2022-04-05 09:30
Hi!

Thanks it is quite clear!
Out of curiosity, do you plan to integrate multiple feeds and multi-components in the future?

Cheers

Michael

**Comment by yoelcortes** [comment] 2022-04-05 13:25
Yeah, it's been on my list for some time now. My projects do not require it, so I'll probably get to it during end of Summer 2022.

Thanks!

**Closed by yoelcortes** 2022-04-05 13:25 UTC
Labels: bug, question
